[package]
  name    = "wasm_zero_addr"
  version = "0.1.0"
  edition = "2024"

[dependencies]

[[bin]]
  name = "main-rs"
  path = "main.rs"

[profile.dev]
  opt-level        = 0
  debug-assertions = false
